[package]
name = "yetanotherclown/net"
description = "A Data-Driven Networking Library, inspired by BridgeNet2 & Bevy_Renet, made for the Matter ECS."
version = "0.5.0"
license = "MIT"
authors = ["YetAnotherClown"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.toml", "wally.lock"]